level1 = [
    "ZZZZZZZZZZZZZZZZZZZZZZZZZ",
    "Z......S.......Z.......EZ",
    "ZZZZZ.ZZZ.ZZZZZZZ.ZZZZZZZ",
    "Z.......Z..Z............Z",
    "Z.ZZZZZ.Z.ZZZZZZZZ.ZZZZ.Z",
    "Z.Z.....Z.......Z...Z...Z",
    "Z.ZZZZZ.ZZZZZZZZZZZ.ZZZ.Z",
    "Z...Z...Z.....Z.......Z.Z",
    "ZZZ.Z.ZZZ.ZZZ.ZZZZZZZ.Z.Z",
    "ZQ..Z.....Z...Z...Z...Z.Z",
    "Z.ZZZZZZZ.ZZZZZ.ZZZZZZZZZ",
    "Z...Q...Z...Z...Z.......Z",
    "ZZZZZZZ.Z.ZZZZZ.Z.ZZZZZZZ",
    "Z...ZQ..Z...R...Z.......Z",
    "Z.Z.ZZZ.ZZZZZZZZ.Z.ZZZZ.Z",
    "Z.Z...Q...Z.....Z...Z...Z",
    "Z.ZZZZZZZZZ.ZZZZZZZ.ZZZ.Z",
    "Z.Q..Q...Q..Z...........Z",
    "ZZZZZZZZZZZZZZZZZZZZZZZZZ",
]

level2 = [
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "X...........S...........X",
    "X.......................X",
    "X.......................X",
    "X....G.............B....X",
    "X.......................X",
    "X..XXXXXXXXXXXXXXXXXXX..X",
    "X..X..Q...Q...Q...Q..X..X",
    "X..X....Q...Q...Q....X..X",
    "X..XXXXXXXXXXXXXXXXXXX..X",
    "X.......................X",
    "X..XXXXXXXXXXXXXXXXXXX..X",
    "X..X.................X..X",
    "X..X........E........X..X",
    "X..XXXXXXXXXXXXXXXXXXX..X",
    "X.......................X",
    "X...Q...Q...Q...Q...Q...X",
    "X.......................X",
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
]

level3 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWW",
    "W.......................W",
    "W........S..............W",
    "W.................ZZ....W",
    "W....Q......Q...Y....XX.W",
    "W...............Y....XX.W",
    "W....Q......Q..YY..XXXXXX",
    "W.............YYY..XXWWWW",
    "W....Q......Q.YXXXXXXWWWW",
    "W.............WWWWWWWWWWW",
    "W...XX........WWWWWWWWWWW",
    "W..XXXX.......WWWWWWWWWWW",
    "XXXWWWXXXXX...Y....WWWWWW",
    "XWWWWWWWW.....YY...WWWWWW",
    "WWWWWWWWWWW...YY...WWWWWW",
    "W.E.WWW........Y...WWWWWW",
    "WZZWWWW...R....Y...WWWWWW",
    "WZZWWWW.......YY...WWWWWW",
    "ZZZZWWW.......YYY..WWWWWW",
]

level4 = [
    "WWWWWWWWWWWWWWWWWWWWWWWWW",
    "W..........S...........W",
    "W.Q..W......W......W...W",
    "W...W.W.W.W.W.W.W.W.W.W.W",
    "W...W.W.W.Q........W.W.WW",
    "W.W.W.W.W.W.W.W.W.W.W...W",
    "W.W.....W.W.....W.W.....W",
    "W.W.W.W.W.W.W.W.W.W.W.W.W",
    "W.W.W.W...W...W...W.W.W.W",
    "W.W.W.W.W.W.W.W.W.W.W.W.W",
    "W...G....Q..............W",
    "W.W.W.W.W.W.W.W.W.W.W.W.W",
    "W...W...W...W...W.W.W.W.W",
    "W.W.W.W.W.W.W.W.W.W.W.W.W",
    "W.W...W.W.....W.W.W.Q.W.W",
    "WBW.W.W.W.W.W.W.W.W.W.W.W",
    "W.....W.W.W.W.W.W.W.W.W.W",
    "W.Q.W.W.W.W...E....W.W.WW",  
    "WWWWWWWWWWWWWWWWWWWWWWWWW",
]

